feature #79: created an admin roles flow
fictadvisor/fictadvisor pull request #100
Opened 2024-01-09 17:20 UTC by illiakroshka

- Added sort by creation date
- Added min and max value for weight
- Added min and max length for display name
- Updated swagger documentation

2024-01-10 10:52 UTC, aim4ik11 submitted a review, later dismissed

2024-02-29 19:36 UTC, igaryakqwe requested changes

2024-02-29 19:36 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/EditRolesPage.tsx
> +            href={`/admin/grants`}
remove curly braces

2024-02-29 19:36 UTC, igaryakqwe commented on fictadvisor-web/src/lib/api/role/RoleAPI.ts
> +      `/roles`,
you doesn't need to use quotes like this

2024-02-29 19:36 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/EditRolesPage.tsx
> +          subheader={`${role.id}`}
remove string literal

2024-02-29 19:36 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/roles-list/RolesList.tsx
> +                    href={`/admin/grants`}
remove curly braces

2024-02-29 19:36 UTC, igaryakqwe commented on fictadvisor-web/src/lib/api/role/RoleAPI.ts
> +}
wtf

2024-03-01 18:11 UTC, igaryakqwe approved these changes

2024-03-01 18:11 UTC, merged