feature #55: added possibility to leave complaints
fictadvisor/fictadvisor pull request #104
Opened 2024-01-09 17:39 UTC by f-ogoog

front:
- сreated a Button on teacher's page that opens pop up
- сreated a pop-up with form

back:
- created endpoint to save and send complaints

closes #55

2024-01-10 09:51 UTC, fokaaas requested changes

2024-01-10 09:51 UTC, fokaaas commented on fictadvisor-api/prisma/schema.prisma
> +  group     Group?   @relation(fields: [groupId], references: [id])
add cascade delete

2024-01-10 09:51 UTC, fokaaas commented on fictadvisor-api/prisma/schema.prisma
> +  teacher   Teacher  @relation(fields: [teacherId], references: [id])
add cascade delete

2024-01-10 09:51 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/ComplaintDTO.ts
> +    fullName: string;
fullName?:

2024-01-10 09:51 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/ComplaintDTO.ts
> +    groupId: string;
groupId?:

2024-01-10 09:51 UTC, fokaaas commented on fictadvisor-api/src/v2/database/repositories/ComplaintRepository.ts
> +export class ComplaintRepository {
you can create a complaint via teacherRepository

2024-01-12 13:32 UTC, fokaaas requested changes

2024-01-12 13:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/TeacherService.ts
> +    if (!code) throw new InvalidEntityIdException('Group');
the exception will never be thrown :)

2024-01-12 18:05 UTC, kujo205 commented on fictadvisor-api/src/v2/api/dtos/ComplaintDTO.ts
> +
@f-ogoog is it possible to not return errors with 
`obj.*`

like here
![image](https://github.com/fictadvisor/fictadvisor/assets/86970828/1baae1f0-9d09-4c05-9c87-b55fa06f8c9a)


but without obj. thing

2024-01-12 19:37 UTC, kujo205 requested changes
why this is commented out

2024-01-12 19:37 UTC, kujo205 commented on fictadvisor-web/src/app/teachers/[teacherId]/page.tsx
> +import GroupAPI from '@/lib/api/group/GroupAPI';
why half of this page is commented out

2024-01-12 19:37 UTC, kujo205 commented on fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
> +                  onClick={submitForm}
why do you need onClick here, just pass `type='submit'`, this will trigger `handleSubmit` function

2024-01-12 19:37 UTC, kujo205 commented on fictadvisor-web/src/lib/api/teacher/TeacherAPI.ts
> +      complaint,
are you sure `AuthorizationHeader` is not needed here?

2024-01-12 19:51 UTC, kujo205 requested changes

2024-01-12 19:51 UTC, kujo205 commented on fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
> +      {({ submitForm }) => (
```suggestion
      {({  }) => (
```

2024-01-12 19:52 UTC, fokaaas approved these changes

2024-01-12 19:56 UTC, kujo205 approved these changes

2024-01-12 20:06 UTC, merged