design #77: Changed role names to icons
fictadvisor/fictadvisor pull request #132
Opened 2024-01-12 04:49 UTC by VladB1l

- Changed role names to icons on survey, subject, teacher page
- Changed the display of the "Інше" and "Екзамени" roles

closes #77

2024-01-12 09:16 UTC, Markusplay requested changes
Roles should be changed on icons only in mobile view. Check issue reqs

2024-01-12 21:04 UTC, igaryakqwe approved these changes

2024-01-12 21:04 UTC, igaryakqwe approved these changes

2024-01-13 09:44 UTC, hoshion requested changes

2024-01-13 09:44 UTC, hoshion commented on fictadvisor-web/src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
> +        <CardRoles roles={roles} isMobile={!isMobile} />
why inverted state?

2024-01-13 11:05 UTC, igaryakqwe approved these changes

2024-01-13 11:05 UTC, hoshion approved these changes

2024-01-13 11:05 UTC, merged