enhancement #114: added new EventType enum
fictadvisor/fictadvisor pull request #142
Opened 2024-01-13 20:22 UTC by kol-oss

- added EventTypeEnum enum
- replaced DisciplineTypeEnum with EventTypeEnum
- replaced sending null with EventTypeEnum.OTHER
- updated Swagger documentation

closes #114

2024-01-15 15:14 UTC, ArtemLyah submitted a review, later dismissed

2024-01-17 09:29 UTC, fokaaas requested changes

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
> +    const teachers = await this.disciplineService.getTeachers(disciplineId, disciplineType as DisciplineTypeEnum ?? null);
You should only use EventTypeEnum with schedule logic

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/AttachLessonDTO.ts
> +    disciplineType: EventTypeEnum;
eventType

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/CreateEventDTO.ts
> +    disciplineType?: EventTypeEnum;
eventType

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/UpdateEventDTO.ts
> +    disciplineType?: EventTypeEnum;
eventType

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/DisciplineTypeResponse.ts
>      description: 'Discipline type',
Fix Swagger doc

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/MainEventInfoResponse.ts
> +    disciplineType: DisciplineTypeResponse | EventTypeEnum;
only EventType

2024-01-17 09:29 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/EventResponse.ts
> +    disciplineType: EventTypeEnum;
eventType

2024-01-20 15:48 UTC, fokaaas submitted a review, later dismissed

2024-01-20 16:42 UTC, fokaaas approved these changes

2024-01-20 16:42 UTC, merged