feature #11: Added filters by cathedra and role on the teachers page
fictadvisor/fictadvisor pull request #152
Opened 2024-01-16 12:38 UTC by JessFreak

- added cathedras to PollController.getPollDisciplineTeachers response
- added cathedras to SubjectController.getTeachers response
- created TeacherWithRolesResponse
- created TeacherWithCathedrasResponse
- created TeacherFullResponse
- refactored teacher responses

closes #11

2024-01-21 16:20 UTC, Markusplay requested changes

2024-01-21 16:20 UTC, Markusplay commented on fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.tsx
> +          key={Math.random()}
Don't use Math random for keys, use cathedra id instead

2024-01-21 18:56 UTC, fokaaas requested changes

2024-01-21 18:56 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/TeacherService.ts
> +      rating: this.getRating(marks),
Since the rating is already in the teacher entity, so it's calculated in the mapper (see getSubject method). So delete it.

2024-01-21 19:06 UTC, fokaaas requested changes

2024-01-21 19:06 UTC, fokaaas commented on fictadvisor-api/src/v2/database/entities/DbDiscipline.ts
> +  teacher: DbTeacher;
```ts
teacher: Teacher & {
    cathedras: (TeachersOnCathedras & {
      cathedra: Cathedra,
    })[];
  };
  ```

2024-01-21 19:06 UTC, fokaaas commented on fictadvisor-api/src/v2/database/entities/DbTeacher.ts
> +  disciplineTeachers?: {
not optional

2024-01-21 19:19 UTC, fokaaas submitted a review, later dismissed

2024-01-21 19:23 UTC, Markusplay requested changes

2024-01-21 19:23 UTC, Markusplay commented on fictadvisor-web/src/components/pages/search-pages/search-form/SearchForm.styles.ts
> +      ? `0px solid transparent}`
remove curly brace

2024-01-21 19:23 UTC, Markusplay commented on fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.tsx
>            key={Math.random()}
As I said before, do not use math random for keys

2024-01-22 19:36 UTC, Markusplay approved these changes

2024-01-23 10:34 UTC, Markusplay approved these changes

2024-01-23 10:34 UTC, merged