feature #154: implemented creating events of type Other through bot
fictadvisor/fictadvisor pull request #169
Opened 2024-01-23 21:38 UTC by VlO-OlV

- Made createEvent, getGroupEvents, deleteEvent and update endpoints accesible from Telegram bot
- Added getGroupEventsByMonth endpoint
- Added query parameter to filter events by type from getFortnightEvents, getGroupEventsByWeek and getGroupEventsByMonth endpoints
- Removed post endpoint

closes #154

2024-01-24 14:32 UTC, dmykyr requested changes
Change EventByIdPipe throw. It should look like: 
`throw new InvalidEntityIdException('Event');`

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
In `update` method you should remove try catch. Because week parameter from body can't be nullable

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +    InvalidGroupIdException:
Also add `InvalidUserIdException`

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/services/ScheduleService.ts
> +    let startWeek = await this.dateService.getWeekByDate(startOfMonth);
`startWeek` is never reassigned. Use `const` instead of `let`

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/services/ScheduleService.ts
> +    let endWeek = await this.dateService.getWeekByDate(endOfMonth);
`endWeek` is never reassigned. Use `const` instead of `let`

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/services/ScheduleService.ts
> +      let weekEvents = await this.getGroupEventsForTelegram(groupId, week, userId, query);
`weekEvents` is never reassigned. Use `const` instead of `let`

2024-01-24 14:32 UTC, dmykyr commented on fictadvisor-api/src/v2/api/services/ScheduleService.ts
> +    const events  = await this.getGroupEventsForTelegram(groupId, week, userId, query);
You can make `query` param nullable in `getGroupEventsForTelegram` method and do not pass extra empty param

2024-01-25 09:48 UTC, dmykyr requested changes

2024-01-25 09:48 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +    //guards: TelegramGuard,
forgot to uncomment row

2024-01-25 09:48 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  //@ApiBearerAuth()
forgot to uncomment row

2024-01-26 11:32 UTC, fokaaas requested changes

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  })
this endpoint must be accessible from bot and also from web, so return permission

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  })
there is no such param

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
>      type: EventResponse,
Describe fields in response

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
>      @Body() body: CreateEventDTO,
Describe fields in body

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  })
the same problem, this endpoint must be accessible from bot and also from web, so return permission

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  })
the same problem

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  @ApiParam({
Also add `@ApiParam()` for eventId

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  })
the same problem

2024-01-26 11:32 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
> +  @ApiParam({
Also add `@ApiParam()` for eventId

2024-01-31 15:02 UTC, closed without merging