bug #156: reset complaint form
fictadvisor/fictadvisor pull request #181
Opened 2024-01-25 16:42 UTC by Arsaide

- added use resetForm function from Formik

closes #156

2024-01-25 19:23 UTC, M-Rybalko approved these changes

2024-01-25 19:33 UTC, Markusplay requested changes

2024-01-25 19:33 UTC, Markusplay commented on fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
> +    { resetForm }: { resetForm: () => void },
why not resetForm: ()=>void

2024-01-25 20:05 UTC, M-Rybalko approved these changes

2024-01-25 20:09 UTC, Markusplay approved these changes

2024-01-26 10:47 UTC, Markusplay approved these changes

2024-01-26 10:48 UTC, merged