feature #118: Create an admin groups flow
fictadvisor/fictadvisor pull request #195
Opened 2024-01-28 19:22 UTC by ArtemLyah

- added admissionYear field in students and groups models
- set groups field optional in student model
- provided migration
- set right admissionYear in database
- updated endpoint for getting all groups
- updated endpoint for creating group
- updated endpoint for updating group
- updated endpoint for deleting group
- created controller for educational program
- updated documentation

closes #118

2024-01-30 11:34 UTC, fokaaas requested changes
Configure the linter!

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/EduProgramController.ts
> +  @Get('/specialitites')
it doesn't belong to this controller

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/EduProgramController.ts
> +  path: '/eduProgram',
`eduprograms`

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/EduProgramController.ts
> +@ApiTags('eduprogram')
Eduprogram

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/GroupController.ts
> +      Educatioal program id cannot be empty
Educational

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/QueryAllGroupDTO.ts
> +    cources?: number[];
courses

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/SpecialityResponse.ts
> +  specialities: SpecialityResponse[];
add indent

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/EduProgramService.ts
> +  }
that method doesn't belong to this service

2024-01-30 11:34 UTC, fokaaas commented on fictadvisor-api/src/v2/database/entities/DbGroup.ts
> +      role: Role,
```ts
roles?: ({
      role: Role,
    } & UserRole)[]
```

2024-02-01 12:08 UTC, fokaaas requested changes

2024-02-03 11:26 UTC, fokaaas requested changes

2024-02-03 11:26 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/GroupService.ts
> +      courceDate.setMonth(courceDate.getMonth()+4);
magic number

2024-02-26 11:20 UTC, igaryakqwe submitted a review, later dismissed

2024-02-26 12:11 UTC, igaryakqwe approved these changes

2024-02-26 14:28 UTC, f-ogoog approved these changes

2024-02-26 16:32 UTC, igaryakqwe approved these changes

2024-02-26 16:35 UTC, f-ogoog approved these changes

2024-02-26 16:35 UTC, merged