feature #154: implemented creating events of type Other through bot
fictadvisor/fictadvisor pull request #201
Opened 2024-01-31 16:58 UTC by VlO-OlV

- Made createEvent, getGroupEvents, deleteEvent and update endpoints accesible from Telegram bot
- Added getGroupEventsByMonth endpoint
- Added query parameter to filter events by type from getFortnightEvents, getGroupEventsByWeek and getGroupEventsByMonth endpoints
- Removed createSimpleTelegramEvent endpoint

closes #154

2024-02-03 17:59 UTC, dmykyr approved these changes

2024-02-23 21:55 UTC, dmykyr submitted a review, later dismissed

2024-02-28 13:36 UTC, f-ogoog requested changes

2024-02-28 13:36 UTC, f-ogoog commented on fictadvisor-api/src/v2/utils/documentation/decorators.ts
> +    }
single telegram guard will be not working

2024-02-28 13:41 UTC, f-ogoog requested changes

2024-02-28 13:41 UTC, f-ogoog commented on fictadvisor-api/src/v2/security/permission-guard/PermissionGuard.ts
> +      }
why using try catch?

2024-03-04 14:30 UTC, f-ogoog approved these changes

2024-03-04 14:31 UTC, merged