feature #108: create an admin main page flow
fictadvisor/fictadvisor pull request #205
Opened 2024-02-01 16:07 UTC by dmykyr

- created necessary files for work with new PageText entity
- implemented getAll updateMany and create methods for PageText
- created permissions for methods restriction
- created update and create DTO for PageTextController methods
- created PageTextsResponse class
- created ResourceMapper class
- refactored ResourceRepository class to the newest realization of methods
- updated existing module files by adding PageText module files
- updated getAll, get, update methods in ResourceService class
- updated entity name in ResourceByIdPipe to correct documentation variant
- updated MapperModule by adding ResourceMapper
- added updateMany method in ResourceService class
- added resource id validation method in ResourceService class

closes #108

2024-02-02 11:04 UTC, fokaaas requested changes

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/PageTextsResponse.ts
> +    @ApiProperty({
not described

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/responses/ResourcesResponse.ts
> +      type: [ResourceResponse],
not described

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/PageTextService.ts
> +    return await DatabaseUtils.paginate<StudentResource>(this.pageTextRepository, body, data);
redundant logic

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/PageTextService.ts
> +      if (!await this.pageTextRepository.exist(pageText.key)) {
use find instead of exist

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/ResourceService.ts
> +    return await DatabaseUtils.paginate<StudentResource>(this.resourceRepository, body, data);
redundant logic

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/ResourceService.ts
> +      if (!await this.resourceRepository.exist(resource.id)) {
use find instead of exist

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/database/repositories/ResourceRepository.ts
> +  }
wrong method in repository

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/mappers/ResourceMapper.ts
> +    };
carefully review the response described in the issue

2024-02-02 11:04 UTC, fokaaas commented on fictadvisor-api/src/v2/security/PERMISSION.ts
> +  PAGES_UPDATE = 'pages.update',
PAGE_TEXTS..

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/dtos/CreatePageTextDTO.ts
> +    @IsNotEmpty(validationOptionsMsg('Link can not be empty'))
make optional

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/dtos/CreatePageTextDTO.ts
> +    })
make optional

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
> +  })
add @ApiUnauthorizedResponse

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
> +      You do not have permission to perform this action`,
@ApiUnauthorizedResponse

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/controllers/ResourceController.ts
> +    NoPermissionException:
add @ApiUnauthorizedResponse

2024-02-08 18:31 UTC, f-ogoog commented on fictadvisor-api/src/v2/api/controllers/ResourceController.ts
> +  })
@ApiUnauthorizedResponse

2024-02-11 16:22 UTC, f-ogoog approved these changes

2024-03-18 09:34 UTC, igaryakqwe requested changes

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.tsx
> +    isShown: boolean;
you can move this type: { value: string; link: string; isShown: boolean } to additional interface to avoid duplicating code

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.tsx
> +  }, []);
you have 2 similar useEffects on this page, try to combine them

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.tsx
> +  }, [studentResources]);
and try to unify the big useEffects

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.tsx
> +            }}
move it to constant

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/lib/api/page-texts/PageTextsAPI.ts
> +      `/pageTexts`,
use simple quotes

2024-03-18 09:34 UTC, igaryakqwe commented on fictadvisor-web/src/lib/api/student-resources/StudentResourcesAPI.ts
> +      `/studentResources`,
use simple quotes

2024-03-27 14:27 UTC, igaryakqwe approved these changes

2024-03-27 15:49 UTC, merged