feature #281: updated poll endpoints for telegram
fictadvisor/fictadvisor pull request #282
Opened 2024-03-02 15:59 UTC by JessFreak

- added Telegram Guard to /v2/poll/teachers/{userId} and /v2/disciplineTeachers/{disciplineTeacherId}/questions endpoints
- created endpoint like /v2/disciplineTeachers/{disciplineTeacherId}/answers with userId in body

closes #281

2024-03-11 12:05 UTC, SharpDevOps10 approved these changes

2024-03-11 12:05 UTC, SharpDevOps10 commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +      UserId can not be empty
`Can not ` -> `cannot`

2024-03-11 12:05 UTC, SharpDevOps10 commented on fictadvisor-api/src/v2/api/dtos/CreateAnswersDTO.ts
> +    description: 'Array of the question`s answers',
Rename to: `'Array of the question\'s answers'`

2024-03-11 12:05 UTC, SharpDevOps10 commented on fictadvisor-api/src/v2/api/dtos/CreateAnswersDTO.ts
> +  @IsNotEmpty(validationOptionsMsg('UserId can not be empty'))
`Can not` -> `cannot`

2024-03-11 15:00 UTC, SharpDevOps10 submitted a review, later dismissed

2024-03-11 16:22 UTC, f-ogoog requested changes

2024-03-21 14:58 UTC, f-ogoog approved these changes

2024-03-21 14:59 UTC, merged