bug #23: other event fields are not visible
fictadvisor/fictadvisor pull request #293
Opened 2024-03-18 13:26 UTC by nnstsya

- added event type checking on schedule card
- removed teacher validation on "other event" type

closes #23

2024-03-18 18:08 UTC, kujo205 requested changes
Good job!

2024-03-18 18:08 UTC, kujo205 commented on fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
> +        {event?.eventType !== 'OTHER' ? (
put this in some descriptive variable like `isDisciplineRelatedEvent`,

otherwise, good job troubleshooting this giant pile of shi...

2024-03-18 18:08 UTC, kujo205 commented on fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx
> +              )}
Here as well, since it's repeated 2 times

2024-03-23 08:11 UTC, kujo205 approved these changes
Good!

2024-03-23 08:13 UTC, igaryakqwe approved these changes

2024-03-23 08:21 UTC, merged