feature #2: added service worker
fictadvisor/fictadvisor pull request #348
Opened 2024-04-05 22:39 UTC by igaryakqwe

- initialized service worker
- added service-worker.js

closes #2

2024-04-11 06:37 UTC, Markusplay approved these changes

2024-04-11 06:48 UTC, Markusplay requested changes

2024-04-11 06:48 UTC, Markusplay commented on fictadvisor-web/public/service-worker.js
Why there are so many console logs?

2024-04-11 07:08 UTC, Markusplay approved these changes

2024-04-12 13:41 UTC, hoshion approved these changes

2024-04-12 13:41 UTC, merged