enhancement/improve-teachers-mapper
fictadvisor/fictadvisor pull request #360
Opened 2024-04-13 20:28 UTC by bohdanbulakh

2024-04-23 14:18 UTC, JessFreak requested changes

2024-04-23 14:18 UTC, JessFreak commented on fictadvisor-api/src/v2/api/dtos/CreateTeacherDTO.ts
> +  @IsEnum(Position, validationOptionsMsg('Position must be an enum'))
add new validation messages to BadRequest of the endpoint that uses this DTO

2024-04-23 14:18 UTC, JessFreak commented on fictadvisor-api/src/v2/api/dtos/UpdateTeacherDTO.ts
> +  @IsEnum(Position, validationOptionsMsg('Position must be an enum'))
add new validation messages to BadRequest of the endpoint that uses this DTO

2024-04-23 20:31 UTC, JessFreak approved these changes

2024-04-24 06:51 UTC, illiakroshka approved these changes

2024-04-24 06:51 UTC, merged