feature #337: implemented an error page for all routes
fictadvisor/fictadvisor pull request #393
Opened 2024-06-27 13:11 UTC by namanica

- created error.tsx file for pages errors handling
- created global-error.tsx file for layouts errors handling
- wrote a temporary design for them

closes #337

2024-06-27 16:27 UTC, oleksandr-korol-hoc requested changes

2024-06-27 16:27 UTC, oleksandr-korol-hoc commented on fictadvisor-web/src/app/error.tsx
> +  useEffect(() => {
we dont need a console.error

2024-06-27 16:27 UTC, oleksandr-korol-hoc commented on fictadvisor-web/src/app/error.tsx
> +    <PageLayout hasFooter={false}>
this component is completely the same as in /src/app/global-error.tsx, so move it to component and reuse in both pages

2024-06-27 16:27 UTC, oleksandr-korol-hoc commented on fictadvisor-web/src/app/global-error.tsx
> +        <PageLayout hasFooter={false}>
DRY

2024-06-28 11:58 UTC, sifes approved these changes

2024-06-28 11:58 UTC, merged