Feature/create endpoint for user creation
fictadvisor/fictadvisor pull request #41
Opened 2024-01-05 19:47 UTC by hoshion

2024-01-06 17:57 UTC, PavloVlasiuk requested changes

2024-01-06 17:57 UTC, PavloVlasiuk commented on fictadvisor-api/src/v2/security/PERMISSION.ts
> +  ADMIN_USER_CREATE = 'admin.users.create',
rewrite the name of this enum element to ADMIN_USERS_CREATE

2024-01-06 17:57 UTC, PavloVlasiuk commented on fictadvisor-api/src/v2/api/controllers/UserController.ts
> +    permissions: PERMISSION.ADMIN_USER_CREATE,
change the name of enum element accordingly

2024-01-07 19:45 UTC, PavloVlasiuk approved these changes

2024-01-08 08:21 UTC, fokaaas requested changes

2024-01-08 08:21 UTC, fokaaas commented on fictadvisor-api/src/v2/security/PERMISSION.ts
> +  ADMIN_USERS_CREATE = 'admin.users.create',
users.create

2024-01-08 10:02 UTC, fokaaas approved these changes

2024-01-11 13:22 UTC, Ksrebniukk approved these changes

2024-01-11 17:21 UTC, fokaaas approved these changes

2024-01-11 17:21 UTC, merged