bug #450: fixed bug on teacher role OTHER
fictadvisor/fictadvisor pull request #458
Opened 2024-09-01 13:47 UTC by sifes

- removed all usages of Teacher Roles enum in DTOs, Responses and other API files
- replaced Teacher Roles by Discipline Types
- removed Teacher Roles enum from database

closes [#450](https://github.com/fictadvisor/fictadvisor/issues/450)

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/.env.development
> +API_BASE_URL=http://localhost:4455/v2
do not forget to change back this

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/disciplines/search/constants/index.ts
> +
remove space

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/groups/edit/[groupId]/constants/index.ts
>  export const rolesOptions = [
no more rolesOptions

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/groups/edit/[groupId]/constants/index.ts
> +  { value: DisciplineTypeEnum.WORKOUT, label: 'Інше' },
there is no 'Інше' now

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/teachers/edit/[teacherId]/constants/index.ts
>  export const rolesOptions = [
no more rolesOptions

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/teachers/search/components/teachers-admin-search/TeachersAdminSearch.tsx
>        cathedrasId: newCathedrasId,
where is the related logic for disciplineType

2024-09-29 11:07 UTC, sifes commented on fictadvisor-web/src/app/admin/teachers/search/constants/index.ts
> +export const teacherRoles: DisciplineTypeEnum[] = [
there is no teacherRoles

2024-10-04 11:28 UTC, dmykyr requested changes

2024-10-04 11:28 UTC, dmykyr commented on fictadvisor-api/src/v2/mappers/TeacherMapper.ts
> +  Position, DisciplineTypeEnum,
move to next row

2024-10-04 11:44 UTC, dmykyr approved these changes

2024-10-04 12:19 UTC, foxsis23 approved these changes

2024-10-04 12:34 UTC, merged