feature #434: add auth with cookies
fictadvisor/fictadvisor pull request #474
Opened 2024-09-02 20:07 UTC by sifes

front:
- update useAuthentication and authenticationContext
- remove blocking rendering
- remove getAuthHeader
- add WithCredentials: true in axios
- add interceptor in axios for updating access_token
- remove AuthService

closes #434

2024-09-07 19:44 UTC, dmykyr approved these changes

2024-09-09 20:24 UTC, Markusplay requested changes

2024-09-09 20:24 UTC, Markusplay commented on fictadvisor-web/src/app/(auth)/register/components/telegram-register-buttons/TelegramRegisterButtons.tsx
> +  ) : (
Move to if statement

2024-09-09 20:24 UTC, Markusplay commented on fictadvisor-web/src/components/common/layout/header/utils/transformData.ts
>    const name = [user?.lastName, user?.firstName, user?.middleName].join(' ');
do we need to check if user is defined, if we already pass non null object?

2024-09-09 20:24 UTC, Markusplay commented on fictadvisor-web/src/lib/api/instance.ts
> +        throw error_1;
do not throw error in catch

2024-09-09 20:24 UTC, Markusplay commented on fictadvisor-web/src/lib/providers/authentication/AuthenticationProvider.tsx
> +const authenticationContext = createContext<AuthenticationContext>({
wtf is it

2024-09-10 05:56 UTC, sifes commented on fictadvisor-web/src/lib/providers/authentication/AuthenticationProvider.tsx
> +const authenticationContext = createContext<AuthenticationContext>({
wait, actually, whats wrong with this

2024-09-10 15:45 UTC, Markusplay approved these changes

2024-09-29 19:33 UTC, merged