feature: added fields to edit page
fictadvisor/fictadvisor pull request #50
Opened 2024-01-05 21:14 UTC by hoshion

feature: added select for admin pages
bugfix: fixed textarea component
feature: fixed pages
feature: added delete endpoint
feature: added create and edit page
feature: added cathedra endpoint
feature: added possibility to change order
feature: added search field
feature: added teachers table
feature: added possibility to change order
feature: added search field
feature: added teachers table

2024-01-07 18:25 UTC, Markusplay requested changes

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/components/teachers-admin-search/TeachersAdminSearch.tsx
> +      console.log(error);
remove console.log

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/components/teachers-admin-search/TeachersAdminSearch.tsx
> +      console.log({ ...values, order, cathedrasId });
remove console.log

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/components/teachers-admin-search/TeachersAdminSearch.tsx
> +              </Box>
Do we need Box empty wrapper around Input ?

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/components/teachers-admin-search/TeachersAdminSearch.tsx
> +              </Box>
Do we need Box empty wrapper around IconButton ?

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/pages/admin/teachers/edit/[teacherId].tsx
> +  console.log(teacherId);
Remove console log.
Update to App router and use new router and useSearchParams hook

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/lib/api/cathedras/types/AllCathedrasResponse.ts
> +}
You already have Pagination interface in `types/api`

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/pages/teachers-admin-edit-page/TeachersAdminEditPage.tsx
> +                        onChange={() => {}}
wtf

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/pages/teachers-admin-edit-page/TeachersAdminEditPage.tsx
> +                    name={'description'}
remove curly braces

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/pages/teachers-admin-edit-page/TeachersAdminEditPage.tsx
> +                        onChange={() => {}}
wtf

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/pages/teachers-admin-edit-page/TeachersAdminEditPage.tsx
> +                        onChange={() => {}}
wtf

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/pages/teachers-admin-edit-page/TeachersAdminEditPage.tsx
> +                  <Typography sx={{ typography: 'h5' }}>Редагування</Typography>
use variant attribute instead of sx here

2024-01-07 18:25 UTC, Markusplay commented on fictadvisor-web/src/components/pages/admin/teachers-admin-page/components/teachers-table/TeachersTable.tsx
> +                    {teacher.lastName} {teacher.firstName[0]}.{' '}
do we need dot after firstname ?

2024-02-18 20:53 UTC, igaryakqwe commented
Change the name of the pr to the correct one

2024-02-18 21:02 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-teachers/search-teacher-admin-page/components/teachers-admin-search/TeachersAdminSearch.tsx
> +  if (isLoading || !data) return <div>Loading...</div>;
Use loader or skeleton instead this div

2024-02-18 21:02 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
> +          return TeacherAPI.getAll(queryObj, PAGE_SIZE, curPage + 1);
Rebase this changes

2024-02-20 11:43 UTC, igaryakqwe approved these changes

2024-02-20 11:43 UTC, igaryakqwe commented on fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/components/edit-teacher-comments/components/comment-text-area/CommentTextArea.tsx
> +    <Stack direction={'row'} alignItems={'center'} gap={'16px'}>
Remove curly braces

2024-02-20 14:56 UTC, igaryakqwe approved these changes

2024-02-20 14:56 UTC, merged