enhancment #501 refactoring teacher controller and service
fictadvisor/fictadvisor pull request #532
Opened 2024-10-07 19:44 UTC by SylvaticGhost

- refactored teacher service and test for it

closes #501

2024-10-08 18:38 UTC, bohdanbulakh requested changes
refactor controller, dtos, responses and swagger documentation, [here](https://github.com/fictadvisor/fictadvisor/pull/524) is an example

2024-10-10 21:47 UTC, SylvaticGhost commented
@bohdanbulakh, I haven't realised the difference between controller and docs in example PR with the current state here. All required changes of the controller was provided in PR #460

2024-10-12 19:43 UTC, bohdanbulakh requested changes

2024-10-12 19:43 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/services/TeacherService.spec.ts
line 249: change description to smth like `should not throw an error ...`

2024-10-12 19:43 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/mappers/TeacherMapper.ts
line 67: add `CathedraResponse[]` as  `getCathedras` method return type

2024-10-12 19:43 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/services/TeacherService.spec.ts
add tests for `getTeacherSubject`, `getAllContacts`, `getUserDisciplineTeachers`, `updateRating` methods

2024-11-26 16:21 UTC, SylvaticGhost commented
@bohdanbulakh

2024-11-26 18:25 UTC, bohdanbulakh approved these changes
format `TeacherService.spec` and `TeacherService` with eslint

2024-11-26 18:26 UTC, merged