enhancement #509: refactored PageText controller
fictadvisor/fictadvisor pull request #552
Opened 2024-12-06 10:28 UTC by DimaBohdan

- Separated documentation of endpoints in PageText controller
- Refactored related DTOs
- Created PageTextByKeyPipe
- Created findByKey in PageText service

closes #509

2024-12-06 14:00 UTC, VlO-OlV requested changes

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  pageTexts: UpdatePageTextDTO[];
Add indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  isShown?: boolean;
Add indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  link?: string;
Add indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  value?: string;
Add indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  key: string;
Add indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  @MaxLength(200, validationOptionsMsg('Link is too long (max: 200)'))
What if real link is longer than 200 symbols?) (remove this validation)

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  @MaxLength(80, validationOptionsMsg('Key is too long (max: 80)'))
Also remove these validations

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/QueryAllPageTextsDTO.ts
>        keys: string[];
Too large indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/CreatePageTextDTO.ts
>        isShown?: boolean;
Too large indentation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/CreatePageTextDTO.ts
> +    @MaxLength(200, validationOptionsMsg('Link is too long (max: 200)'))
Remove this validation

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/CreatePageTextDTO.ts
> +    @MaxLength(500, validationOptionsMsg('Value is too long (max: 500)'))
Remove these validations

2024-12-06 14:00 UTC, VlO-OlV commented on utils/src/requests/CreatePageTextDTO.ts
> +    @MaxLength(80, validationOptionsMsg('Key is too long (max: 80)'))
Remove these validations

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +      `,
Move this to the previous line

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +      Key is too long (max: 80)
Remove this messages as this validation must be removed from dto

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +      Value is too long (max: 500)
Same

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +      Link is too long (max: 200)
Same

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/getAllTexts.ts
> +      `,
Move this to the previous line

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/create.ts
> +      `,
Move this to the previous line

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/create.ts
> +      Key is too long (max: 80)
Remove this messages as this validation must be removed from dto

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/create.ts
> +      Value is too long (max: 500)
Same

2024-12-06 14:00 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/create.ts
> +      Link is too long (max: 200)
Same

2024-12-06 16:34 UTC, VlO-OlV commented on fictadvisor-api/src/v2/api/pipes/PageTextByKeyPipe.ts
> +
When all requested changes will be completed remove unused imports

2024-12-06 20:08 UTC, VlO-OlV requested changes

2024-12-06 20:08 UTC, VlO-OlV commented on utils/src/requests/UpdatePageTextsDTO.ts
> +  MinLength,
Remove unused imports

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +import { ApiDocumentationParams } from '../decorators';
Name of the documentation file (updateByKey.ts) must be the same as corresponding controller method (updateMany.ts)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateByKey.ts
> +export const PageTextDocumentationUpdateByKey: ApiDocumentationParams = {
Name of the documentation object (PageTextDocumentationUpdateByKey) must be the same as corresponding controller method (PageTextDocumentationUpdateMany)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/index.ts
> +  GET_ALL_TEXTS: PageTextDocumentationGetAllTexts,
Name of the documentation property (GET_ALL_TEXTS) must be the same as corresponding controller method (GET_ALL)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/index.ts
> +  UPDATE_BY_KEY: PageTextDocumentationUpdateByKey,
Name of the documentation property (UPDATE_BY_KEY) must be the same as corresponding controller method (UPDATE_MANY)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/getAllTexts.ts
> +export const PageTextDocumentationGetAllTexts: ApiDocumentationParams = {
Name of the documentation object (PageTextDocumentationGetAllTexts) must be the same as corresponding controller method (PageTextDocumentationGetAll)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/pageText/getAllTexts.ts
> +import { ApiDocumentationParams } from '../decorators';
Name of the documentation file (getAllTexts.ts) must be the same as corresponding controller method (getAll.ts)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
> +    documentation: PageTextDocumentation.UPDATE_BY_KEY,
Name of the documentation property (UPDATE_BY_KEY) must be the same as corresponding controller method (UPDATE_MANY)

2024-12-06 20:08 UTC, VlO-OlV commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
> +    documentation: PageTextDocumentation.GET_ALL_TEXTS,
Name of the documentation property (GET_ALL_TEXTS) must be the same as corresponding controller method (GET_ALL)

2024-12-07 14:09 UTC, bohdanbulakh requested changes

2024-12-07 14:09 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
>    @Patch()
create validation pipe for validating page text key and add  in `@Body()` of this method instead of validation in service

2024-12-07 14:09 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/services/PageTextService.ts
- remove `pageTextsValidation` method
- key in update method will be validated in `@Body()` of controller

2024-12-07 14:09 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/utils/documentation/pageText/updateMany.ts
> +      PageText with such key is not found`,
```suggestion
    InvalidEntityIdException:
      PageText with such key is not found`,
```

2024-12-07 19:07 UTC, bohdanbulakh requested changes

2024-12-07 19:07 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
>    ) {
we must pass an array in this pipe, but our request is an object, so we need to pass a value of `pageTexts` property 
```suggestion
    @Body('pageTexts', ValidatePageTextsPipe) body: UpdatePageTextsDTO,
  ) {
```

2024-12-07 20:13 UTC, bohdanbulakh requested changes

2024-12-07 20:13 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/PageTextController.ts
>    ) {
```suggestion
    @Body(ValidatePageTextsPipe) body: UpdatePageTextsDTO,
  ) {
```

2024-12-07 20:13 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/pipes/ValidatePageTextsPipe.ts
> +    for (const pageText of pageTexts) {
```suggestion
  async transform (body: UpdatePageTextsDTO): Promise<UpdatePageTextsDTO> {
    for (const pageText of body.pageTexts) {
```

2024-12-07 20:13 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/pipes/ValidatePageTextsPipe.ts
> +  }
```suggestion
    return body;
  }
```

2024-12-07 20:33 UTC, bohdanbulakh approved these changes

2024-12-07 20:39 UTC, VlO-OlV approved these changes

2024-12-07 20:39 UTC, merged