enhancement #511: Refactor Discipline entity
fictadvisor/fictadvisor pull request #559
Opened 2024-12-09 01:01 UTC by goritpukan

- Change some methods names in service
- Change some methods names in comtroller
- Refactor swagger documentation in controller 
- Add more validation to DTO's
- Add documentation to DTO's

closes #511

2024-12-09 12:30 UTC, bohdanbulakh requested changes

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
>      return { teachers };
use mapper here, not in service

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
>    @Get(':disciplineId')
```suggestion
  })
  @Get('/:disciplineId')
```

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/utils/documentation/discipline/updateById.ts
> +  },
use default resqponses

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
>    async create (
add mehod return type

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
> +  ) {
add mehod return type

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
>    @Patch('/:disciplineId')
add mehod return type

2024-12-09 12:30 UTC, bohdanbulakh commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
go to `DisciplineMapper`:
- add return types for each method
- rename all mapper methods, they must match such pattern: if the method returns object of type `{SomeType}Response` its name must be `get{SomeType}`

2024-12-10 19:02 UTC, goritpukan commented on fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
if it returns array, but type name is something like BaseDisciplineResponse[], should i name method getBaseDisciplines or getBaseDiscipline?

2024-12-10 22:25 UTC, bohdanbulakh requested changes

2024-12-11 00:11 UTC, bohdanbulakh approved these changes

2024-12-11 00:12 UTC, merged