enhancement #502: refatored Subject entity
fictadvisor/fictadvisor pull request #562
Opened 2024-12-10 10:08 UTC by ReGeNss

- created documentation files for each SubjectController endpoint
- refactored CreateSubjectDTO, QueryAllSubjectDTO, UpdateSubjectDTO
closes #502

2024-12-10 17:10 UTC, VlO-OlV requested changes

2024-12-10 17:10 UTC, VlO-OlV commented on utils/src/requests/UpdateSubjectDTO.ts
> +  })
Add IsString decorator with validation message and also add that message to documentation

2024-12-10 17:10 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/subject/create.ts
> +                  Name can not be empty
```suggestion
                  Name cannot be empty
```

2024-12-10 17:10 UTC, VlO-OlV commented on fictadvisor-api/src/v2/utils/documentation/subject/update.ts
> +                  Name can not be empty
```suggestion
                  Name cannot be empty
```

2024-12-10 17:10 UTC, VlO-OlV commented on utils/src/requests/CreateSubjectDTO.ts
>    @IsNotEmpty(validationOptionsMsg('Name can not be empty'))
```suggestion
  @IsNotEmpty(validationOptionsMsg('Name cannot be empty'))
```

2024-12-10 17:10 UTC, VlO-OlV commented on utils/src/requests/UpdateSubjectDTO.ts
>    @IsNotEmpty(validationOptionsMsg('Name can not be empty'))
```suggestion
  @IsNotEmpty(validationOptionsMsg('Name cannot be empty'))
```

2024-12-10 17:10 UTC, VlO-OlV commented on utils/src/requests/QueryAllSubjectDTO.ts
> +}
This dto must inherit properties from QueryAllDTO, then some of the properties here can be deleted (page, pageSize, search, order). After that you need to update the messages in documentation.

2024-12-10 21:06 UTC, ReGeNss commented on fictadvisor-api/src/v2/api/controllers/SubjectController.ts
> +  ): Promise<void> {
![image](https://github.com/user-attachments/assets/2fefcd97-bf26-4aa3-a9fc-1c4b90bb0dcf)
But this endpoint doesn't return anything

2024-12-12 20:18 UTC, VlO-OlV approved these changes

2024-12-12 20:23 UTC, merged