feature #82: added ability to delete comments
fictadvisor/fictadvisor pull request #83
Opened 2024-01-08 11:23 UTC by Dmutre

Created delete in QuestionAnswerRepository
Created DELETE disciplineTeachers/:questionId/:disciplineTeacherId/:userId/comment endpoint Created delete method to QuestionAnswerRepository
Added permission
Added Swagger documentation
closes #82

2024-01-08 12:15 UTC, hoshion requested changes

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +  @Delete('/:questionId/:disciplineTeacherId/:userId/comment')
You don't have a conceptual understading what is a controller. A Controller is a bunch of endpoints which interacts with a specific entity/domain/field of project/sphere, etc. In this case, this controller intented to work with DisciplineTeacher entity. Thus, all endpoints should be connected to the discipline teacher. 

At the same time, your endpoint starts with ":questionId" param. It's not correct. It should start with ":disciplineTeacher". You can see the example at the endpoint above that edits comment. You need to have "/:disciplineTeacherId/comment" path and then use body object to define what comment should be deleted

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +    @Param('questionId', QuestionByIdPipe) questionId: string,
Not needed (see comment above)

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +    @Param('userId', UserByIdPipe) userId: string
Not needed (see comment above)

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +  ) {
Need to add body object with information about comment (questionId, etc) for deletion

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +  @ApiParam({
Not needed (see comment above)

2024-01-08 12:15 UTC, hoshion commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +  @ApiParam({
Not needed (see comment above)

2024-01-08 14:12 UTC, hoshion approved these changes

2024-01-08 14:12 UTC, hoshion approved these changes

2024-01-09 11:25 UTC, fokaaas requested changes

2024-01-09 11:25 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +    `,
extra carriage return

2024-01-09 11:25 UTC, fokaaas commented on fictadvisor-api/src/v2/api/dtos/DeleteCommentDTO.ts
> +export class DeleteCommentDTO {
Also inherit UpdateCommentDTO from DeleteCommentDTO

2024-01-09 11:25 UTC, fokaaas commented on fictadvisor-api/src/v2/api/services/DisciplineTeacherService.ts
> +      }
use linter

2024-01-09 11:25 UTC, fokaaas commented on fictadvisor-api/src/v2/database/repositories/QuestionAnswerRepository.ts
> +  delete(args: Prisma.QuestionAnswerDeleteArgs) {
linter

2024-01-09 11:25 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
> +  @ApiOkResponse()
add response (deleted comment)

2024-01-10 11:25 UTC, fokaaas approved these changes

2024-01-10 11:26 UTC, merged