enhancement #84: updated swagger for teachers
fictadvisor/fictadvisor pull request #91
Opened 2024-01-08 22:33 UTC by VlO-OlV

- updated getTeacherRoles endpoint
- updated getSubjects endpoint
- updated getDisciplines endpoint
- updated getSubject endpoint
- updated getTeacher endpoint

closes #84

2024-01-09 20:46 UTC, dmykyr requested changes
Also change exception throwing in TeacherByIdPipe file.  It should look like: 
`throw new InvalidEntityIdException('teacher');`

2024-01-09 20:46 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      description: `InvalidEntityId:\n
Incorrect response descritpion. It should look like: 
```
description: `\n
response_name:
  response_possible_text`,
```

2024-01-09 20:46 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      description: `InvalidEntityId:\n
Incorrect response descritpion. It should look like: 
```
description: `\n
response_name:
  response_possible_text`,
```

2024-01-09 20:46 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      description: `NoPermissionException:\n
Incorrect response descritpion. It should look like: 
```
description: `\n
response_name:
  response_possible_text`,
```

2024-01-09 20:46 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>                    teacher with such id is not found
Incorrect response descritpion. It should look like: 
```
description: `\n
response_name:
  response_possible_text`,
```

2024-01-09 20:46 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      description: `InvalidEntityIdException:\n
Incorrect response descritpion. It should look like: 
```
description: `\n
response_name:
  response_possible_text`,
```

2024-01-10 08:24 UTC, dmykyr requested changes
Additionaly you need to change exception throwing in SubjectByIdPipe file. It should look like: `throw new InvalidEntityIdException('Subject');`

2024-01-10 08:27 UTC, dmykyr requested changes

2024-01-10 08:27 UTC, dmykyr commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
> +      Teacher with such id is not found subject with such id is not found`,
All entities in InvalidEntityIdException must start with capital letter, so second text should look like: 
`Subject with such id is not found`

2024-01-10 11:28 UTC, illiakroshka commented
One more task you need to update response body in this endpoint:
![image](https://github.com/fictadvisor/fictadvisor/assets/116638814/cd33b779-9350-482b-bab9-28e0b380440d)

2024-01-12 09:47 UTC, dmykyr approved these changes

2024-01-12 10:29 UTC, illiakroshka approved these changes

2024-01-13 14:57 UTC, fokaaas requested changes

2024-01-13 14:57 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      type: TeacherRolesResponse,
Pls add description
![image](https://github.com/fictadvisor/fictadvisor/assets/114052215/5e3d70e4-91b3-4b51-9924-4c256a29ee8f)

2024-01-13 14:57 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      type: SubjectsResponse,
Also add description
![image](https://github.com/fictadvisor/fictadvisor/assets/114052215/99721a62-2439-4e78-a2f8-871c9664feac)

2024-01-13 14:57 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
> +  })
Add description

2024-01-13 14:57 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>      type: DisciplineTeacherAndSubjectResponse,
Add descriptions
![image](https://github.com/fictadvisor/fictadvisor/assets/114052215/4745b457-2611-421d-85b7-d9b2d087eb6a)

2024-01-13 14:57 UTC, fokaaas commented on fictadvisor-api/src/v2/api/controllers/TeacherController.ts
>    @Get('/:teacherId/disciplines')
Also add unauthorized exception

2024-01-17 09:44 UTC, fokaaas approved these changes

2024-01-17 09:44 UTC, merged